const myths = ["Myth: How Long You Sleep is All That Matters. Sleep duration is important, but it’s not the end-all, be-all. Sleep quality is another critical factor to consider, and it is closely connected with sleep continuity and avoiding sleep disruptions. Fragmented sleep marked by numerous awakenings can interfere with the ability to properly move through the sleep cycle, decreasing time spent in the most restorative stages of sleep. For this reason, every person’s goal should be to sleep enough hours and for those hours to include high-quality, uninterrupted sleep.", 
"Myth: A Good Sleeper Doesn’t Move at Night. Minor movements of the body can occur during normal, healthy sleep. ", 
"Myth: Your Brain Shuts Down During Sleep. The brain remains active during sleep. Its patterns of activity change during different sleep stages, and in rapid eye movement (REM) sleep, brain activity ramps up to a level that shares similarities with when you’re awake.Far from shutting down, shifts in brain activity during sleep are believed to be part of why sleep is critical to effective thinking, memory, and emotional processing.", 
"Myth: Dreaming Only Happens During REM Sleep. The most intense dreams usually happen during REM sleep, but dreaming can occur during any sleep stage9. Dreams in REM and non-REM sleep usually have different content with more vivid or bizarre dreams usually taking place during REM stages.",
"Myth: Adults Sleep More With Age. Older adults frequently sleep less than younger people. Aging can affect a person’s circadian rhythm and make it harder for them to sleep as long as they want. Other health problems that increase with age, such as arthritic pain, may also interfere with a good night’s sleep.",
"Myth: Napping Makes Up for Lack of Sleep at Night. While a quick nap can provide a boost of energy, it’s not a substitute for quality sleep at night, especially because it doesn’t involve moving through the stages of sleep in the same way as during nightly sleep.Many people who get insufficient sleep try to use naps to catch up on sleep, but this often just throws their sleep schedule further out-of-whack by making it harder to fall asleep at a normal bedtime. Long naps can also mean waking up disoriented and sluggish.Though napping isn’t necessarily bad, relying on naps to try to cope with regular sleep deprivation isn’t a winning approach. When you do need a nap, it’s best to keep it shorter than 30 minutes and early in the afternoon.",
"Myth: If You Can’t Sleep, It’s Best to Stay in Bed Until You Fall Back Asleep. Sleep experts recommend getting out of bed if you can’t fall asleep within 20 minutes. Instead of tossing and turning in bed, it’s better to get up, do something relaxing in a quiet and dim setting (without using your cell phone or other electronic devices), and then try to go back to bed. The reason experts advise this approach is that it’s important to associate your bed with sleep. Staying in bed while struggling to sleep can do the exact opposite, linking your bed with a feeling of frustration.",
"Myth: Exercising At Night Disturbs Sleep. Data from surveys and research studies indicates that even vigorous exercise at night does not usually affect sleep. In fact, working out at night helps many people sleep better.That said, for some people, it may not be beneficial to do extremely intense workouts immediately before going to bed as this may make it hard for your body to relax and settle into sleep.",
"Myth: Sleeping With a Light On is Harmless. Even when you’re in bed with your eyes closed, low light can increase the risk of awakenings and may have negative effects on circadian rhythm. Studies have also found that sleeping with too much light in your bedroom can increase eye strain20 and may be associated with notable weight gain. To promote higher-quality sleep and a more stable circadian rhythm, it’s best to sleep in a bedroom that’s as close to pitch darkness as possible."
]

export default myths;